name: VuePress CI
on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: "14"

    - name: Setup VuePress
      run: yarn global add vuepress

    - name: Install node modules
      run: yarn

    - name: VuePress Build
      run: |
        vuepress build
