name: VuePress CI
on:
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: "14"

    - name: Setup VuePress
      env:
        SSH_PRIVATE: ${{ secrets.DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE" > ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        yarn global add vuepress

    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-nodemodules-

    - name: Install node modules
      run: yarn

    - name: VuePress Deploy
      run: |
        yarn deploy

    - name: Upload to IPFS
      uses: aquiladev/ipfs-action@v1
      with:
        path: ./.vuepress/dist/

    - name: Commit
      run: |
        (git add . && git commit -m "Actions: Update" && git push -f) || true
